### ISSUE TITLE
How to find "really unknown" cases?

### ISSUE THREAD

**Issue by gnufinder** [alex-konovalov/gnu#109]
I would suggest to show the numbers below 50,000 , for which no calculation has yet be done.
This would help to concentrate on the really unknown values. The wishlist contains entries, for which
the value is either not known exactly or not verified, but a calculation is already done.

It would be nice to have a list of the "really unknown" cases.

**Comment by olexandr-konovalov** [comment]
Keeping this in the database (to be available from the GAP level) would cause extra administrative load and create an extra overhead by expanding the commit history since each value would require two commits instead of one. Keeping this somewhere else would still require bookkeeping and it will be hard to keep that list in sync. My suggestion is to use the GitHub interface to check for the values which are currently being processed. For example, if you will enter "gnu(5440)" (with quotes to specify that you're searching for the exact line) and then click on "issues" tab in the search results, you will find freshly submitted gnu(5440). This is one of the reasons to follow the rules of submitting new values as specified in CONTRIBUTING.md.

Also, if someone tried to calculate something but did not managed to get the exact value (because of sublists) or it's not yet replicated, this should not stop others from trying to do the same - "duplication is replication" so it will be useful and will be good to report.
